# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy web app to Azure Static Web Apps

env:
  APP_LOCATION: "./earth-sea-game-client/dist" # location of your client code

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    env:
        working-directory: ./earth-sea-game-client
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true


      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
            version: 8
            run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
         echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
            path: ${{ env.STORE_PATH }}
            key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
                ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{env.working-directory}}

      - name: Build
        run: pnpm run build
        working-directory: ${{env.working-directory}}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@latest
        with:
          skip_api_build: true
          skip_app_build: true
          azure_static_web_apps_api_token: ${{ secrets.EARTHSEAGAMESWATOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ''
          output_location: ''

